config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # REST
  resources :hotels
  # get     '/hotels',              to: 'hotels#index',  as: :hotels
  # get     '/hotels/new',          to: 'hotels#new',    as: :new_hotel
  # post    '/hotels',              to: 'hotels#create'
  # get     '/hotels/:popo',        to: 'hotels#show',   as: :hotel
  # get     '/hotels/:popo/edit',   to: 'hotels#edit',   as: :edit_hotel
  # put     '/hotels/:popo',        to: 'hotels#update'
  # patch   '/hotels/:popo',        to: 'hotels#update'
  # delete  '/hotels/:popo',        to: 'hotels#destroy'

  resources :phones
  resources :semaphores

  get '/states/:id/semaphores', to: "states#semaphores", as: :state_semaphore

  root to: "hotels#index"

  # _path
  # hotel_path => '/hotels/:popo' method: :put
  # hotel_path(1) => '/hotels/1' method: :put

  # _url
  # hotel_url(1) => 'http://localhost/hotels/1'

  # CRUD = de algo
  # get => pedir cosas
  # post => crear cosas
  # put y patch => actualizar cosas
  # delete => eliminar cosas

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hotel.rb
class Hotel < ApplicationRecord
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :state  
end

app/models/semaphore.rb
class Semaphore < ApplicationRecord
  # Relaciones
  belongs_to :state

  # Enums
  enum color: [:verde, :amarillo, :naranja, :rojo]

  # Callbacks
  before_validation :set_end_date

  # validaciones 
  validates :color, inclusion: { in: %w(verde amarillo naranja rojo), message: "%{value} no está permitido" }

  def self.get_latest_by_states
    all_semaphores = self.all.order(start: :desc)
    latest_semaphores = {}

    all_semaphores.each do |asem|
      # if(true)
      #   #do something
      # end
      # unless(false)
      #   # do something
      # end
      unless(latest_semaphores[asem.state_id])
        latest_semaphores[asem.state_id] = asem
      end
    end

    latest_semaphores
  end

  private
  def set_end_date
    (self.end = self.start + 2.weeks) if self.start && !self.end
  end
end

app/models/state.rb
class State < ApplicationRecord
  has_many :phones
  has_many :semaphores
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :get_hotel, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:index, :show]
  # before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]


  # Acciones
  def index
    @hotels = Hotel.all
  end

  def new
    @hotel = Hotel.new
  end

  def create
    @hotel = Hotel.create(hotels_params)
    redirect_to hotel_path(@hotel.id)
  end

  def show
  end
  
  def edit
  end
  
  def update
    @hotel.update(hotels_params)
    redirect_to hotel_path(@hotel.id)
  end
  
  def destroy
    @hotel.destroy
    redirect_to hotels_path
  end

  private

  def get_hotel
    @hotel = Hotel.find(params[:id])
  end

  def hotels_params
    params.require(:hotel).permit(:name, :stars)
  end
  # {
  #   hotel: {
  #     name: "some value", -
  #     stars: "4", -
  #     address: "asbdabsdbasd", 
  #   }
  # }
  # {name: "some value", stars: "4", pemitted: true}
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  # Ejecutar la función get_phone antes de las siguientes acciones:
  # - edit
  # - update
  # - show
  # - destroy
  before_action :get_phone, only: [:edit, :update, :show, :destroy]

  # Acciones
  def index
    @phones = Phone.all
  end

  def new
    @phone = Phone.new
  end

  def create
    @phone = Phone.create(phone_params)
    redirect_to @phone
  end

  def edit
  end

  def update
    @phone.update(phone_params)
    redirect_to show
  end

  def show
  end

  def destroy
    @phone.destroy
    redirect_to phones_path
  end
  
  private
  # Strong params
  def phone_params
    params.require(:phone).permit(:state_id, :number)
  end

  def get_phone
    @phone = Phone.find(params[:id])
  end
end

app/controllers/semaphores_controller.rb
class SemaphoresController < ApplicationController
  before_action :get_semaphore, only: [:show, :edit, :update]
  def index
    @semaphores = Semaphore.all
  end

  def new
    @semaphore = Semaphore.new
  end

  def create
    @semaphore = Semaphore.create!(semaphore_params)
    redirect_to @semaphore
  end

  def show
  end

  def edit
  end

  def update
  end

  private
  def semaphore_params
    params.require(:semaphore).permit(:state_id, :color, :start)
  end

  def get_semaphore
    @semaphore = Semaphore.find(params[:id])
  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  def semaphores
    @state = State.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/semaphores_helper.rb
module SemaphoresHelper
end

app/views/hotels/edit.html.erb
<h1>Holis, estoy editando</h1>
<%= form_with model: @hotel, local: true do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :stars %>
    <%= form.number_field :stars %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/hotels/index.html.erb
<h1>Holis</h1>
<%= link_to "Crear hotel", new_hotel_path %>
<% @hotels.each do |hotel| %>
<p><span style="font-weight: bold">Nombre:</span> <%= hotel.name %></p>
<p><span style="font-weight: bold">Estrellas:</span> <%= hotel.stars %></p>
<div class="acciones">
  <a href="<%= hotel_path(hotel.id) %>">Ver detalles</a><!-- show -->
  <a href="<%= edit_hotel_path(hotel.id) %>">Editar</a><!-- edit -->
  <%= link_to "Eliminar", hotel_path(hotel.id), method: :delete %><!-- destroy -->
</div>
<hr>
<% end %>
<% if user_signed_in? %>
  <%= link_to "Cerrar sesión", destroy_user_session_path, method: "delete" %>
<% else %>
  <%= link_to "Iniciar sesión", new_user_session_path %>
<% end %>

app/views/hotels/new.html.erb
<h2>Hola soy la acción new</h2>
<%= form_with model: @hotel, local: true do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :stars %>
    <%= form.number_field :stars %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/hotels/show.html.erb
<h1>Holis, soy el que te lo muestra</h1>
<% if @hotel %>
<p><span style="font-weight: bold">Nombre:</span> <%= @hotel.name %></p>
<p><span style="font-weight: bold">Estrellas:</span> <%= @hotel.stars %></p>
<% else %>
<p>No existe el hotel</p>
<% end %>
<%= link_to "ver hoteles", hotels_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyecto</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="notice" style="margin-top: 2rem"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert" style="margin-top: 2rem"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/phones/_form.html.erb
<%= form_with(model: phone, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :state_id, "Estado*"%>
    <%= form.select(:state_id, options_for_select(State.all.pluck(:name, :id), phone.state_id), {include_blank: true}, {class: "form-select", required: true}) %>
  </div>

  <div class="form-group">
    <%= form.label :number, "Número telefónico*" %>
    <%= form.text_field :number, class: "form-control", required: true %>
  </div>

  <%= form.submit class: "btn btn-primary mt-3" %>
<% end %>

app/views/phones/edit.html.erb
<div class="container">
  <h1>Editando el teléfono asociado al estado <%= @phone.state.name %></h1>
  <%= render 'form', phone: @phone %>
</div>

app/views/phones/index.html.erb
<h1>Teléfonos registrados</h1>
<%= link_to "crear uno", new_phone_path, class: "btn btn-secondary" %>
<% @phones.each do |phone| %>
  <div>
    <h3>Estado: <%= phone.state.name %></h3>
    <p>Telefono: <%= phone.number %></p>
    <%= link_to "Más información", phone, class: "btn btn-primary" %>
    <%= link_to "Editar", edit_phone_path(phone), class: "btn btn-success" %>
    <%= link_to "Eliminar", phone, method: :delete, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/phones/new.html.erb
<div class="container">
  <h1>Creando un nuevo teléfono</h1>
  <%= render 'form', phone: @phone %>
</div>

app/views/phones/show.html.erb
<div class="container">
  <h1>Observando el teléfono del estado <%= @phone.state.name %></h1>
  <p>Este es un teléfono que sirve para poder contestar llamadas</p>
  <p>Teléfono: <strong><%= @phone.number %></strong></p>
  <%= link_to "Regresar", phones_path, class: "btn btn-primary" %>
</div>

app/views/semaphores/_form.html.erb
<%= form_with(model: semaphore, local: true) do |f| %>
  <div class="form-group">
    <%= f.label :state_id, "Estado*"%>
    <%= f.select :state_id, options_for_select(State.all.pluck(:name, :id), semaphore.state_id), {include_blank: true}, {class: "form-control", required: true}%>
  </div>
  <div class="form-group">
    <%= f.label :color, "Color del semáforo*" %>
    <%= f.select :color, options_for_select(Semaphore.colors.map{|s| [s.first.capitalize, s.first]}, semaphore.color), {include_blank: true}, {class: "form-control", required: true} %>
  </div>
  <div class="form-group">
    <%= f.label :start, "Fecha de inicio*" %>
    <%= f.date_field :start, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :end, "Fecha de finalización" %>
    <%= f.date_field :end, class: "form-control" %>
  </div>
  <%= f.submit class: "btn btn-primary mt-3" %>
<% end %>

app/views/semaphores/edit.html.erb
<h1>Semaphores#edit</h1>
<p>Find me in app/views/semaphores/edit.html.erb</p>

app/views/semaphores/index.html.erb
<div class="container">
  <div class="d-flex justify-content-around">
    <h1>Semaforo por estado</h1>  
    <%= link_to "dar de alta", new_semaphore_path, class: "btn btn-primary align-self-center" %>
  </div>
  <div class="d-block">
    <% @semaphores.each do |sem| %>
      <div class="w-100">
        <h3>El estado <%= sem.state.name.capitalize %> estuvo en semáforo <%= sem.color.titleize %></h3>
        <p>de <%= sem.start %> al <%= sem.end %></p>
      </div>
      <hr>
    <% end %>
  </div>
</div>

app/views/semaphores/new.html.erb
<div class="container">
  <div class="d-flex justify-content-around">
    <h1>Creando un nuevo semáforo</h1>
    <%= link_to "regresar", semaphores_path, class: "btn btn-secondary align-self-center" %>
  </div>
  <%= render 'form', semaphore: @semaphore %>
</div>

app/views/semaphores/show.html.erb
<div class="container mt-3">
  <div class="d-flex justify-content-around">
    <h1>Semáforo del estado de <%= @semaphore.state.name.capitalize %></h1>
    <div class="d-flex">
    <%= link_to "ver semáforos", semaphores_path, class: "btn btn-primary align-self-center" %>
    <%= link_to "Histórico del estado", state_semaphore_path(@semaphore.state_id), class: "btn btn-secondary align-self-center" %>
    </div>
  </div>
  <ul>
    <li><strong>Color:</strong> <%= @semaphore.color.capitalize %></li>
    <li><strong>Fecha de inicio:</strong> <%= @semaphore.start %></li>
    <li><strong>Fecha de finalización:</strong> <%= @semaphore.end %></li>
  </ul>
</div>

app/views/states/semaphores.html.erb
<div class="container mt-3">
  <div class="d-flex justify-content-around">
    <h1 class="text-center">Historial del estado de <%= @state.name.capitalize %></h1>
    <%= link_to "Crear semáforo", new_semaphore_path, class: "btn btn-secondary align-self-center" %>
  </div>
  <% @state.semaphores.each do |sem| %>
    <ul>
      <li><strong>Color:</strong> <%= sem.color.capitalize %></li>
      <li><strong>Fecha inicio:</strong> <%= sem.start %></li>
      <li><strong>Fecha fin:</strong> <%= sem.end %></li>
    </ul>
    <hr>
  <% end %>
</div>